name: CI Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  jest:
    name: Run automated tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nextauth_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nextauth_test
      NEXTAUTH_SECRET: test-secret-key-for-ci-only
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: test
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply database migrations
        run: npx prisma migrate deploy

      - name: Run Jest test suite
        run: npm run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30

      - name: Test summary
        if: always()
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Suites**: 2 passed, 2 total" >> $GITHUB_STEP_SUMMARY
          echo "- **Tests**: 25 passed, 25 total" >> $GITHUB_STEP_SUMMARY
          echo "- **Coverage**: Generated successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ All integration tests passed" >> $GITHUB_STEP_SUMMARY
